### ISSUE TITLE
[配方管理]连续编辑配方出现的错误

### ISSUE THREAD

**Issue by chenyork** [hjyk/tbsui#14]
Admin登录状态，对R005点编辑，改允差、比例，点保存都没有问题，版本也会正常跳转，但是再进行编辑，改允差和比例，不点保存，而是点可读，跳框选择放弃修改之后，版本号不会变化，但是配方中的内容是被修改了的
结论，第一次编辑修改是正确没有问题的，连着第二次编辑修改任何一个内容，甚至删除比例和允差中的数值为空白，点击只读，放弃修改，依然会出现可以修改的情况，但是换一个user或者重新登录一次，数据又会出现。只读是个啥意思？

**Comment by chenyork** [comment]
无法重现

**Comment by Haiji** [comment]
重现步骤：  1.选择一个配方 编辑并保存。2. 紧接着继续编辑，但是点只读按钮。提示框选确定。
