### ISSUE TITLE
[物料管理]禁用物料的逻辑确认

### ISSUE THREAD

**Issue by chenyork** [hjyk/tbsui#16]
将物料的状态改为禁用时，系统提示：该物料正被配方使用，不可禁用。这个设置不合理。
禁用物料不受配方影响，可以单独禁用，禁用的物料在已经生成的订单中正常显示，新建配方以及选择有该物料的配方是不能使用。

**Comment by chenyork** [comment]
原来的需求不一致，需要再讨论。

**Comment by Haiji** [comment]
保持现有逻辑。   考虑下包含禁用物料的配方进行编辑的时候。  编辑之后的配方如果包含禁用的物料，不让用户保存。 换句话说，配方的保存总是校验其是否包含了禁用的无聊。
