### ISSUE TITLE
[整体功能]增加 OrderNum, RecipeNum, MaterialNum,UserID校验

### ISSUE THREAD

**Issue by Haiji** [hjyk/tbsui#24]
因为：
1. 太长了，界面会乱掉。
2. 可能出现在条码里面的字段，只能是字符和数字。 中文等在条码中无法打印。

1.OrderNum, RecipeNum, MaterialNum 18位，只允许输入字母和数字，不允许输入中文或者特殊字符。
2. UserID 也同样限制，但是长度最多8.
3.前端校验即可。小写字母自动转大写。

**Comment by chenyork** [comment]
在blur事件里面做key字段的格式化，去除字母和数字以外的字符，并且转为大写。Max Length写在input控件上，通过浏览器来限制最大长度。
