### ISSUE TITLE
[物料]物料禁用的逻辑

### ISSUE THREAD

**Issue by chenyork** [hjyk/tbsui#28]
物料禁用时，在编辑配方时，下拉列表不应该包含它。
如果现有配方已经存在这个无效的物料，则需要照常显示，但是不能保存。

**Comment by Haiji** [comment]
@chenyork  如果这个不好做的话，那么做成这样： 下拉框中不出现禁用的物料。配方中已经存在的禁用物料不用下拉框，直接显示文字。不允许修改禁用物料那行，用户只能删除禁用的物料。
