### ISSUE TITLE
[用户管理]管理员权限的逻辑

### ISSUE THREAD

**Issue by JohnGriffithLondon** [hjyk/tbsui#29]
1.管理员只能改操作员的密码，不能改管理员的密码。
2.设置一个超级账号，归技术服务保管，必要时找技服修改密码。

**Comment by Haiji** [comment]
管理员就是超级账号。 只有一个admin。

**Comment by chenyork** [comment]
目前预留了一个SYSADMIN作为系统管理员，但是不建议归技术服务人员保管，可以交给客户自行保管。因为改密码的操作不需要技术服务人员介入。

如果有需要，可以改成。
1.只有SYSADMIN有权创建管理员和修改管理员密码。
2.管理员只能修改个人信息（包括密码），不能创建管理员，不能修改其他管理员的任何信息。
3.操作员无法进入用户管理页面，不能做任何操作。

**Comment by Haiji** [comment]
我的建议：
1.只有SYSADMIN可以打开用户管理
2.任何用户可以通过点击当前用户名来弹出密码修改界面。
-----------------------------------------------------
实现： 增加一个页面专门用户密码修改。
显示：当前用户名，姓名。
输入：当前密码，两次新密码。
--------------------------------------------
这个样子逻辑清晰，也增加不多工作量。

**Comment by Haiji** [comment]
确认：
1. 只有SYSADMIN能进入用户管理模块，他可以改包括自己的任何人的信息密码。
2. 用户管理和称设置模块只有SYSADMIN能进去。 其他人包括管理员都不能进去。
